### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by chpr1510** [joeVenner/Python-Chat-Gui-App#1]
hi,
I have executed your files without any changes but I am getting the message in the same chat box, the message is not transferred to another chatbox.
---------------
no errors found
libraries and modules are installed
----------------
Please check
![Screenshot (1110)](https://user-images.githubusercontent.com/54094195/133981726-6524df38-892e-44d1-ba2b-de8520788de7.png)

**Comment by joeVenner** [comment]
Hi There,

Sorry for late reply. i just doubled check the script & it's working fine. please just try to run it again & follow the steps below.

1st : open server.py in cmd (terminal) and luch the script first ( **make sure u run the server file first before client** )

2nd : open the client file in another cmd and lunch it ( python client.py )

3rd : open again another terminal window and lunch client.py


![image](https://user-images.githubusercontent.com/61122897/134786592-9c3e5c4a-bee6-4a39-a698-48f49809a58a.png)

**Comment by miraccan00** [comment]
It's working 💯

**Comment by chpr1510** [comment]
its working now sorry for the issue
