### ISSUE TITLE
can't connect on a different computer

### ISSUE THREAD

**Issue by zarlicho** [joeVenner/Python-Chat-Gui-App#2]
i tried it on two different computers and why it can't connect, i already use the same one connection

**Comment by zarlicho** [comment]
![image](https://user-images.githubusercontent.com/63176268/145665206-6f4ee6f1-7915-473b-85cf-e1e016819f6f.png)

**Comment by joeVenner** [comment]
The app is developed to be used only on a local computer, but you can do it easily by just changing the Ip of the server from localhost to the server IP address [ Code in [Line 19](https://github.com/joeVenner/Python-Chat-Gui-App/blob/a27211912a7af993788e2f7b4efe6706c95e84b4/server.py#L19) ]
Then the same thing in the client file, change the localhost IP address to the actual IP of the client [ Code in [Line
](https://github.com/joeVenner/Python-Chat-Gui-App/blob/a27211912a7af993788e2f7b4efe6706c95e84b4/client.py#L24) ]
Make sure that the port that both the client and the server can listen on the port **[remote_port = 10319 #TCP port]**

**Comment by zarlicho** [comment]
ok i'm trying
